"""empty message

Revision ID: d390d593b4ff
Revises: 83a87c120b78
Create Date: 2018-12-30 23:12:34.836947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd390d593b4ff'
down_revision = '83a87c120b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('creat_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'creat_time')
    # ### end Alembic commands ###
